### PR TITLE
Feature/docker

### PR DESCRIPTION
**Pull request by jason-fox**
This PR Updates the NGI Proxy Docker build to do the following

* Switch to build from source rather than use npm
* Remove git after use to minimize layers
* Default to fixed Node version (using the same base image as iot-agents)
* ~Encapsulate with pm2 by default~
* Add missing license
* Update documentation

### CODE REVIEW

**Comment by aarranz** [comment]
PR looks good to me, except pm2 part. Why to use a process manager taking into account that we are using docker? docker-compose/docker swarm has support for restarting dead or unhealthy containers. Moreover, docker-compose/swarm allows you to configure restart policy, how to detect if the container is unhealthy, and so on. By using pm2 in the proposed way (not providing a way for configuring pm2), we are fixing the behaviour removing flexibility and not adding any feature.

In fact, some of the bugs FICODES has fixed on the IoTAgents are related to having IoTAgents entering in zombie mode (process running but not working as expected) problems that were not fixed by adding pm2. So, in my honest opinion, pm2 is not providing any advantage on the IoTAgents images.

**Comment by jason-fox** [comment]
@aarranz  - I'll remove `pm2` for now, but ideally I'd like to get a common way forward for this. I only added it in the first place for consistency with the IoT Agents.

Whether `pm2` is a good thing, a bad thing or neither, I'd leave to the [discussion thread](https://github.com/telefonicaid/iotagent-node-lib/issues/790)

**Comment by jason-fox** [comment]
> PR looks good to me, except pm2 part.

`pm2` removed (at least for now) . Fixed:  0e5b9e5, 62a5b22

**Comment by aarranz** [comment]
I don't know why coverage decreased, as you are not changing the code nor the tests...

**Pull request merged**
